### ISSUE TITLE
标签疑问

### ISSUE THREAD

**Issue by zhaozhiyi11** [iCVTEAM/CTDNet#2]
请问edge = cv2.imread(self.cfg.datapath + '/edge/' + name + '_edge.png', 0).astype(np.float32)，edge指的是目标标签边界的二值图像吗？

**Comment by Elitphil** [comment]
作者好像没给出如何制作二值边界图像，一笔带过说制作边界图像是很容易的。

**Comment by Elitphil** [comment]
作者好像没给出如何制作二值边界图像，一笔带过说制作边界图像是很容易的

**Comment by uyi618** [comment]
> 假设edge = cv2.imread(self.cfg.datapath + '/edge/' + name + '_edge.png', 0).astype(np.float32)，edge指的是目标标签的二值图像吗？
你好，那个edge文件夹放的是什么文件呢？您弄清楚了吗，能不能分享一下

**Comment by zhaozhiyi11** [comment]
> 

你好我目前是使用opencv生成标签的边界，放在edge文件夹里的。

**Comment by uyi618** [comment]
> > 
> 
> 你好我现在是用opencv生成标签的想要，放在边缘那个里的。

您好，能不能加一下联系方式，有些问题想咨询一下，谢谢。q1217240802

**Comment by uyi618** [comment]
你好，或者你看能不能给一个联系方式呀？有点事情想请教一下，拜托了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "iCVTEAM/CTDNet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月20日(星期六) 下午3:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [iCVTEAM/CTDNet] 标签疑问 (Issue #2)





   
你好我目前是使用opencv生成标签的边界，放在edge文件夹里的。
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by uyi618** [comment]
> > 
> 
> 你好我现在是用opencv生成标签的想要，放在边缘那个里的。
你好，或者你看能不能给一个联系方式呀？有点事情想请教一下，拜托了

**Comment by zhaozhiyi11** [comment]
这是我mask转edge的代码


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "iCVTEAM/CTDNet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月20日(星期六) 下午5:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [iCVTEAM/CTDNet] 标签疑问 (Issue #2)





    
你好我现在是用opencv生成标签的想要，放在边缘那个里的。
 你好，或者你看能不能给一个联系方式呀？有点事情想请教一下，拜托了
  
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by uyi618** [comment]
你好 那个 代码在哪的 没看到啊？


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "iCVTEAM/CTDNet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月20日(星期六) 晚上8:47
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [iCVTEAM/CTDNet] 标签疑问 (Issue #2)





 这是我mask转edge的代码 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "iCVTEAM/CTDNet"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2021年11月20日(星期六) 下午5:52 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [iCVTEAM/CTDNet] 标签疑问 (Issue #2) 
 
 
 
 
 
      
 你好我现在是用opencv生成标签的想要，放在边缘那个里的。 
  你好，或者你看能不能给一个联系方式呀？有点事情想请教一下，拜托了 
    
 — 
 You are receiving this because you authored the thread. 
 Reply to this email directly, view it on GitHub, or unsubscribe. 
 Triage notifications on the go with GitHub Mobile for iOS or Android. 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zhaozhiyi11** [comment]
> 你好 那个 代码在哪的 没看到啊？
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "iCVTEAM/CTDNet" ***@***.***&gt;; 发送时间:&nbsp;2021年11月20日(星期六) 晚上8:47 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [iCVTEAM/CTDNet] 标签疑问 (Issue #2) 这是我mask转edge的代码
> ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 发件人: "iCVTEAM/CTDNet" ***@***.***&amp;gt;; 发送时间:&amp;nbsp;2021年11月20日(星期六) 下午5:52 ***@***.***&amp;gt;; ***@***.******@***.***&amp;gt;; 主题:&amp;nbsp;Re: [iCVTEAM/CTDNet] 标签疑问 (Issue #2) 你好我现在是用opencv生成标签的想要，放在边缘那个里的。 你好，或者你看能不能给一个联系方式呀？有点事情想请教一下，拜托了 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.



代码：
import os
import os.path as osp
import cv2
import numpy as np

path="E:\\3. The cropped image tiles and raster labels\\test\\rename_test_label"
image_files=os.listdir(path)
save_path = "E:\\3. The cropped image tiles and raster labels\\test\\label_edge"

for i in range(len(image_files)):
    image = image_files[i]
    portion = os.path.splitext(image)
    image_name = portion[0] + '.tif'
    image_id = int(portion[0])

    data = cv2.imread(osp.join(path,image))
    gray = cv2.cvtColor(data, cv2.COLOR_BGR2GRAY)

    draw_img = np.zeros((512, 512), dtype=np.uint8)
    bimg, contours, hier = cv2.findContours(gray, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    res = cv2.drawContours(draw_img, contours, -1, (255, 255, 255), 2)
    cv2.imwrite(osp.join(save_path,image),res)

**Comment by uyi618** [comment]
> > 你好 那个 代码在哪的 没看到啊？
> > […](#)
> > ------------------ 原始邮件 ------------------ 发件人: "iCVTEAM/CTDNet" _**@**_._**>; 发送时间: 2021年11月20日(星期六) 晚上8:47 _**@**_.**_>; _**@**_._**_**@**_.**_>; 主题: Re: [iCVTEAM/CTDNet] 标签疑问 (Issue #2) 这是我mask转edge的代码
> > ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "iCVTEAM/CTDNet" _**@**_._**&gt;; 发送时间:&nbsp;2021年11月20日(星期六) 下午5:52 _**@**_.**_&gt;; _**@**_._**_**@**_.**_&gt;; 主题:&nbsp;Re: [iCVTEAM/CTDNet] 标签疑问 (Issue #2) 你好我现在是用opencv生成标签的想要，放在边缘那个里的。 你好，或者你看能不能给一个联系方式呀？有点事情想请教一下，拜托了 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.
> 
> 代码： import os import os.path as osp import cv2 import numpy as np
> 
> path="E:\3. The cropped image tiles and raster labels\test\rename_test_label" image_files=os.listdir(path) save_path = "E:\3. The cropped image tiles and raster labels\test\label_edge"
> 
> for i in range(len(image_files)): image = image_files[i] portion = os.path.splitext(image) image_name = portion[0] + '.tif' image_id = int(portion[0])
> 
> ```
> data = cv2.imread(osp.join(path,image))
> gray = cv2.cvtColor(data, cv2.COLOR_BGR2GRAY)
> 
> draw_img = np.zeros((512, 512), dtype=np.uint8)
> bimg, contours, hier = cv2.findContours(gray, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
> res = cv2.drawContours(draw_img, contours, -1, (255, 255, 255), 2)
> cv2.imwrite(osp.join(save_path,image),res)
> ```

谢谢

**Comment by zhaozhiyi11** [comment]
import os
import os.path as osp
import cv2
import numpy as np

path="E:\\3. The cropped image tiles and raster labels\\test\\rename_test_label"
image_files=os.listdir(path)
save_path = "E:\\3. The cropped image tiles and raster labels\\test\\label_edge"

for i in range(len(image_files)):
    image = image_files[i]
    portion = os.path.splitext(image)
    image_name = portion[0] + '.tif'
    image_id = int(portion[0])

    data = cv2.imread(osp.join(path,image))
    gray = cv2.cvtColor(data, cv2.COLOR_BGR2GRAY)
    # 寻找轮廓
    draw_img = np.zeros((512, 512), dtype=np.uint8)
    bimg, contours, hier = cv2.findContours(gray, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    res = cv2.drawContours(draw_img, contours, -1, (255, 255, 255), 2)
    cv2.imwrite(osp.join(save_path,image),res)
